name: ml-hype-or-hybris
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - scikit-image
  - scikit-learn
  - ipywidgets
  - pandas
  - rise
  - seaborn
  - folium
  - opencv
  - pip
  - pip:
    - sodapy
