name: ml-hype-or-hybris
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7

  # Extend the Jupyter Notebook experience
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - start_jupyter_cm

  # Necessary libraries for obligatory material
  - scikit-image
  - scikit-learn
  - pandas
  - rise
  - seaborn

  # This is only needed for '05 weiterfuehrende-beispiele'
  - ipywidgets
  - folium
  - opencv
  - pip
  - pip:
    - sodapy
